version: '3.7'

services:
    backend:
        build:
            context: ./backend/vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
        image: sail-8.1/app
        environment:
            DB_HOST: db
            DB_DATABASE: snapp_pay
            DB_USERNAME: root
            DB_PASSWORD: root
            SNAPPPAY_GRANT_TYPE: password
            SNAPPPAY_CLIENT_ID: 2
            SNAPPPAY_CLIENT_SECRET: L8erqTADUWRjv8TsAVWjlkSn2abyIekuK6mcgJV2
        ports:
            - 8080:8080
        volumes:
            - ./backend:/app/backend
        depends_on:
            - db


        networks:
            - app

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        tty: true
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app/frontend
        depends_on:
            - backend
        networks:
            - app

    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: 'snapp_pay'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
        networks:
            - app

networks:
    app:
        driver: bridge
