#!/usr/bin/env bash

if [ ! -z "sail" ]; then
    usermod -u sail sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer
# chown -R sail:sail /var/www/html
# php artisan migrate:fresh --seed

if [ $# -gt 0 ]; then
    exec gosu sail "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
